### ISSUE TITLE
Schema for IOS Simulator

### ISSUE THREAD

**Issue by hpng6** [cashfree/core-ios-sdk#57]
Hi,
While build the code in simulator, is is showing error.
Plz help me schema for IOS simulater
Thanq.

**Comment by hpng6** [comment]
![IMG-20221116-WA0011](https://user-images.githubusercontent.com/16951742/202400599-a4684866-3dfc-4337-b939-3f5d2db797d0.jpg)

**Comment by suhas-cashfree** [comment]
Hi,
You might be using a deprecated version of our ios SDK.

**Comment by suhas-cashfree** [comment]
Please use this documentation -> https://docs.cashfree.com/docs/ios-native
Please reach out to [care@cashfree.com](mailto:care@cashfree.com) for more information

**Comment by suhas-cashfree** [comment]
Closing this issue
